language: java

jdk:
  - openjdk11

gradle:
  - 7.3.2

sudo: false

env:
  global:
    - CODECOV_TOKEN=4678d1b8-676a-47d4-92f1-dd5b1f833326

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)


before_install:
      - wget https://services.gradle.org/distributions/gradle-7.3.3-bin.zip
      - unzip -qq gradle-7.3.3-bin.zip
      - export GRADLE_HOME=$PWD/gradle-7.3.3
      - export PATH=$GRADLE_HOME/bin:$PATH
      - gradle -v

notifications:
  email:
    recipients:
      - semykinru@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always